apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: function-rds-metrics-xr-ref
spec:
  compositeTypeRef:
    apiVersion: example.crossplane.io/v1
    kind: XR
  mode: Pipeline
  pipeline:
  - step: fetch-rds-metrics-from-xr-name
    functionRef:
      name: function-rds-metrics
    input:
      apiVersion: rdsmetrics.fn.crossplane.io/v1beta1
      kind: Input
      databaseNameRef: "xr.metadata.name"
      region: "us-west-2"
      metrics:
      - "CPUUtilization"
      - "DatabaseConnections"
      - "FreeableMemory"
      - "FreeStorageSpace"
      period: 300
      target: "context.metricsResult"
    credentials:
      - name: aws-creds
        source: Secret
        secretRef:
          namespace: crossplane-system
          name: aws-creds